apiVersion: apps/v1
kind: Deployment
metadata:
  name: tree
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: root
          image: helmcontainer.azurecr.io/dockerr:latest
          ports:
            - containerPort: 80
          # Add the following sections for LivenessProbe and ReadinessProbe
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readiness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          # Add the following section to read the ConfigMap
          envFrom:
            - configMapRef:
                name: myapp configmap
          # Add the rolling update strategy
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 1
