apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: your-registry-name.azurecr.io/your-image-name:tag
          ports:
            - containerPort: 80
          # Add the following sections for LivenessProbe and ReadinessProbe
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readiness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          # Add the following section to read the ConfigMap
          envFrom:
            - configMapRef:
                name: my-app-config-map
          # Add the rolling update strategy
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 1
